### ISSUE TITLE
Further automated tests

### ISSUE THREAD

**Issue by shadowwalkersb** [GorgonCryoEM/Gorgon#91]
Here is a list of possible tests that can be done in an automated way. They are listed under Gorgon's Actions menu. 
@GorgonCryoEM/developers , do you think we should prepare tests for all the cases or only for a few of them?
- Secondary Structure Element
  - [x] Find SSE Correspondences
  - [x] Identify SSEs
  - [ ] Predict SSE from Sequence
- C-alpha atoms
  - [ ] Fit to density
- Skeleton
  - [x] Laplacian Smoothing
- Volume
  - [x] Normalize
  - [x] Downsample
  - [x] Crop
  - [x] Laplacian Smoothing
  - Skeletonization
    - [x] ~~Interactive~~
    - [x] Binary
    - [x] Grayscale

/cc #39

**Comment by g5v991x** [comment]
all of them....

**Comment by taoju** [comment]
Since these features are quite different, I would say test as many of them as possible automatically.

I don't know if all of them can be automated; functions like interactive skeletonization and identify SSEs require user input to operate. But part of these functions can be tested (e.g., computing scored pseudo atoms during the identification of SSEs).
